name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["needs-triage"]
assignees:
  - dostuffthatmatters
body:
  - type: markdown
    attributes:
      value: |
        **🍀 Thanks for taking the time to fill out this bug report!**
  - type: textarea
    id: description
    attributes:
      label: Descriptions
      description: Describe the bug. Add logs, screenshots, etc. Markdown syntax supported.
    validations:
      required: true
  - type: input
    id: pyra-version
    attributes:
      label: Pyra Version
      placeholder: 4.X.Y
    validations:
      required: true
  - type: input
    id: opus-version
    attributes:
      label: OPUS Version
      placeholder: 7.8.* / 8.2.* / ...
    validations:
      required: false
  - type: input
    id: camtracker-version
    attributes:
      label: CamTracker Version
      placeholder: 3.9.* / ...
    validations:
      required: false
  - type: input
    id: windows-version
    attributes:
      label: Windows Version
      placeholder: 10 / ...
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Your `config.json` file
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: json
    validations:
      required: false
