name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["needs-triage"]
assignees:
  - dostuffthatmatters
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Pyra Version
      placeholder: 4.X.Y
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OPUS Version
      placeholder: 7.8.* / 8.2.* / ...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: CamTracker Version
      placeholder: 3.9.* / ...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Windows Version
      placeholder: 10 / ...
    validations:
      required: false
  - type: textarea
    id: configuration
    attributes:
      label: Your `config.json` file
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
