const colors = require('tailwindcss/colors');
const customColors = {
    // colors used from https://tailwindcss.com/docs/customizing-colors
    blue: {
        50: '#eff6ff',
        75: '#e5f0fe',
        100: '#dbeafe',
        150: '#cde2fe',
        200: '#bfdbfe',
        300: '#93c5fd',
        400: '#60a5fa',
        500: '#3b82f6',
        600: '#2563eb',
        700: '#1d4ed8',
        800: '#1e40af',
        900: '#1e3a8a',
        950: '#0f1d45',
    },
    gray: {
        50: '#f8fafc',
        75: '#f4f7fa',
        100: '#f1f5f9',
        150: '#e9eef4',
        200: '#e2e8f0',
        250: '#d6dee8',
        300: '#cbd5e1',
        350: '#afbccc',
        400: '#94a3b8',
        450: '#7c8ba1',
        500: '#64748b',
        600: '#475569',
        700: '#334155',
        750: '#283548',
        800: '#1e293b',
        850: '#162032',
        900: '#0f172a',
        950: '#0B111F',
    },
    green: {
        50: '#f0fdf4',
        75: '#e6fced',
        100: '#dcfce7',
        150: '#cbf9db',
        200: '#bbf7d0',
        300: '#86efac',
        400: '#4ade80',
        500: '#22c55e',
        600: '#16a34a',
        700: '#15803d',
        800: '#166534',
        900: '#14532d',
        900: '#14532d',
        950: '#0a2916',
    },
    red: {
        50: '#fef2f2',
        75: '#feeaea',
        100: '#fee2e2',
        150: '#fed6d6',
        200: '#fecaca',
        300: '#fca5a5',
        400: '#f87171',
        500: '#ef4444',
        600: '#dc2626',
        700: '#b91c1c',
        800: '#991b1b',
        900: '#7f1d1d',
        950: '#3f0e0e',
    },
    yellow: {
        50: '#fefce8',
        75: '#fefad5',
        100: '#fef9c3',
        150: '#fef4a6',
        200: '#fef08a',
        300: '#fde047',
        400: '#facc15',
        500: '#eab308',
        600: '#ca8a04',
        700: '#a16207',
        800: '#854d0e',
        900: '#713f12',
        950: '#381f09',
    },
    orange: colors.orange,
    teal: colors.teal,
    rose: colors.rose,
    'rose-75': '#ffeaec',
    cyan: colors.cyan,
};

/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: ['class'],
    content: ['./index.html', './src/**/*.{html,js,ts,tsx}'],
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            fill: customColors,
            colors: {
                ...customColors,
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: 0 },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: 0 },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require('tailwindcss-animate'), require('@tailwindcss/forms')],
};
