name: "build-on-release"
on:
  push:
    branches:
      - release

defaults:
  run:
    working-directory: packages/ui

jobs:
  publish-tauri:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version number from package.json
        run: echo "PYRA_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Print version number
        run: echo "Building UI for PYRA version $PYRA_VERSION"

      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: set up bun
        uses: oven-sh/setup-bun@v2

      - name: set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: install dependencies
        run: bun install

      - name: build image
        run: bun run tauri build

      - name: create draft release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: v${{ env.PYRA_VERSION }}
          name: v${{ env.PYRA_VERSION }} (generated by CI)
          draft: true
          prerelease: true
          body: "TODO: description"
          files: |
            src-tauri/target/release/bundle/msi/Pyra.UI_${{ env.PYRA_VERSION }}_x64_en-US.msi
            src-tauri/target/release/bundle/nsis/Pyra.UI_${{ env.PYRA_VERSION }}_x64-setup.exe
