name: 'build-on-release'
on:
    push:
        branches:
            - release

defaults:
    run:
        working-directory: packages/ui

jobs:
    publish-tauri:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install app dependencies and build it
              run: yarn && yarn build
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
                  releaseName: 'App v__VERSION__'
                  releaseBody: 'TODO: release description'
                  releaseDraft: true
                  prerelease: true
