name: "test-python-code"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "packages/core/ui/**"
      - "packages/core/docs/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE.md"
      - "netlify.toml"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test-python-code.yaml"
  pull_request:
    branches:
      - main
      - integration-*
    paths-ignore:
      - "packages/core/ui/**"
      - "packages/core/docs/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE.md"
      - "netlify.toml"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test-python-code.yaml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python 3.10.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install ".[dev]"

      - name: Run Pytests
        run: |
          pytest -m "ci" --cov=packages tests
          coverage report
