name: "test-typescript-codebase-on-main"
on:
  push:
    branches:
      - main
    paths:
      - "packages/ui/**"
      - ".github/workflows/test-typescript-codebase-on-main.yml"
  pull_request:
    branches:
      - main
      - integration-*
    paths:
      - "packages/ui/**"
      - ".github/workflows/test-typescript-codebase-on-main.yml"

defaults:
  run:
    working-directory: packages/ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4

    - name: Set up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20


      - name: Install dependencies
        run: bun install

      - name: Build frontend
        run: bun run build
