name: "test-python-codebase-on-main"
on:
  push:
    branches:
      - main
    paths-ignore:
      - "packages/core/ui/**"
      - "packages/core/docs/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE.md"
      - "netlify.toml"
      - ".github/workflows/*.yml"
      - "!.github/workflows/test-python-codebase-on-main.yml"
  pull_request:
    branches:
      - main
      - integration-*
    paths-ignore:
      - "packages/core/ui/**"
      - "packages/core/docs/**"
      - ".gitignore"
      - "README.md"
      - "LICENSE.md"
      - "netlify.toml"
      - ".github/workflows/*.yml"
      - "!.github/workflows/test-python-codebase-on-main.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # check-out repo and set-up python
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.10.11"
          pdm-version: "2.11.2"
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Run Pytests
        run: |
          pdm run -v pytest -m "ci" --cov=packages tests
          coverage report
